# Session settings
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        name: JSESSIONID  # Custom name for the session cookie
        http-only: true   # Make the cookie HTTP-only to prevent client-side access
        secure: false      # Send cookie only over HTTPS (enable in production)
        path: /           # Path for the session cookie
      timeout: 1m        # Session timeout set to 30 minutes
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{X-Request-ID}] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com:
      app:
        controllers: DEBUG
        services: DEBUG
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 10
spring:
  cache:
    cache-names: "skus,products,vendors,otp,otpAttempts"
    caffeine:
      skus: "maximumSize=500,expireAfterAccess=600s"
      products: "maximumSize=500,expireAfterAccess=600s"
      otpCache: "maximumSize=200,expireAfterAccess=600s"
      attemptsCache: "maximumSize=200,expireAfterAccess=600s"
  threads:
    virtual:
      enabled: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 48210583b24f35
    password: 
    properties.mail.smtp:
      auth: true
      starttls.enable: true
application:
  snr:
    local_url: http://localhost:8080/api
    dev_url: https://snr.ngrok.dev/api
  jwt_config:
    issuer: SubNRenewal
    secret: 
    access_exp_time: 1800 #Short-lived (e.g., 15 minutes, 1 hour).
    refresh_exp_time: 7776000000  #Stored securely on the client.
  vendor_config:
  customer_config:
    otp_verification_enabled: false
    verify_otp: false
    otp_exp_time: 60  #In seconds
    otp_no_of_retry: 3  #In seconds
    email_token_exp: 3600
    address_valid_keys:
      - name
      - address1
      - address2
      - city    
      - state
      - zipCode
      - state
      - country
  sms_providers:
    fast2sms:
      api_key:
      route: q #otp q-->Quick SMS
      url: https://www.fast2sms.com/dev/bulkV2
      flash: 1
    vonage:
      url: https://rest.nexmo.com/sms/json
      api_key:
      api_secret:
      from_brand: SubNRenewal
  cache_config: #In minutes
    db_data_TTL: 360
    db_data_max_size: 5000
    otp_TTL: 5
    otp_max_size: 2500
