# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI-CID with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: s713278/subnrenewals
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      #Deploy the pushed image on Linode Server
      - name: Deploy to Linode instance
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 172.105.33.153
          username: root
          #key: ${{ secrets.LINODE_SSH_PRIVATE_KEY }}
          password: Mithra!@2025
          script: |
            # Install Docker if it's not installed
            #if ! command -v docker &> /dev/null
            #then
            #  echo "Docker not found, installing..."
            #  sudo apt-get update
            #  sudo apt-get install -y docker.io
            #  sudo systemctl start docker
            #  sudo systemctl enable docker
            #fi
            
            # Pull the Docker image from Docker Hub
            docker pull s713278/subnrenewals:latest
            
            # Stop and remove any running container with the same name (optional)
            docker ps -q --filter "name=subscriptions-container" | grep -q . && docker stop subscriptions-container && docker rm subscriptions-container
            
            # Run the Docker container (use docker-compose if needed)
            docker run -d -p 80:80 --name subscriptions-container s713278/subnrenewals:latest
